@host=http://localhost:3000

### Fetch currencies
GET {{host}}/api/external/currencies

### Fetch currency details
GET {{host}}/api/external/currency/BHD

### Convert between currencies
GET {{host}}/api/external/currency/convert?from=NOK&to=BHD&amount=1